import { StyleSheet } from "react-native";
import { COLORS, SPACING, TYPOGRAPHY } from "../shared/constants";

export const appStyles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "stretch",
    backgroundColor: COLORS.white,
  },
  title: {
    fontSize: TYPOGRAPHY.sizes.giant,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.small,
  },
  subtitle: {
    fontSize: TYPOGRAPHY.sizes.lg,
    color: COLORS.textTertiary,
    marginBottom: SPACING.xxxl,
  },
  buttonContainer: {
    width: "100%",
    gap: SPACING.element,
    paddingHorizontal: SPACING.element,
    paddingVertical: SPACING.medium,
  },
  button: {
    backgroundColor: COLORS.info,
    paddingVertical: SPACING.element,
    paddingHorizontal: SPACING.container,
    borderRadius: SPACING.borderRadiusLarge,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: SPACING.small,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
  },
  plansList: {
    flex: 1,
    width: "100%",
  },
  plansListContent: {
    paddingHorizontal: SPACING.container,
    paddingVertical: SPACING.element,
    paddingTop: SPACING.xs,
    gap: SPACING.xxl,
  },
  planCardWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.small,
    marginBottom: SPACING.medium,
    marginTop: SPACING.xs,
  },
  planCard: {
    flex: 1,
    backgroundColor: COLORS.secondaryBackground,
    borderRadius: SPACING.borderRadiusLarge,
    padding: SPACING.element,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  deleteButton: {
    backgroundColor: COLORS.danger,
    width: 44,
    height: 44,
    borderRadius: SPACING.borderRadius,
    justifyContent: "center",
    alignItems: "center",
  },
  planName: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  planExercises: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textTertiary,
  },
  headerWithButton: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACING.container,
    paddingVertical: SPACING.element,
    backgroundColor: COLORS.white,
  },
  compactHeader: {
    width: "100%",
    paddingHorizontal: SPACING.container,
    paddingBottom: SPACING.element,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  kebabButton: {
    padding: SPACING.small,
  },
  doneButtonText: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.info,
  },
  compactTitle: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    marginBottom: 0,
    paddingTop: SPACING.xs,
  },
  compactSubtitle: {
    fontSize: TYPOGRAPHY.sizes.xs,
    color: COLORS.textTertiary,
    fontWeight: TYPOGRAPHY.weights.medium,
    marginTop: SPACING.xs,
  },
  createButton: {
    backgroundColor: COLORS.info,
    paddingVertical: SPACING.small,
    paddingHorizontal: SPACING.element,
    borderRadius: SPACING.borderRadius,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
  },
  createButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: TYPOGRAPHY.weights.semibold,
  },
  loadingText: {
    fontSize: TYPOGRAPHY.sizes.lg,
    color: COLORS.textTertiary,
    textAlign: "center",
    marginTop: SPACING.container,
  },
  emptyText: {
    fontSize: TYPOGRAPHY.sizes.lg,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginTop: SPACING.container,
    fontStyle: "italic",
  },
  divider: {
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    marginTop: SPACING.xs,
    marginBottom: SPACING.element,
  },
  formContainer: {
    paddingHorizontal: SPACING.container,
    paddingVertical: SPACING.xxl,
    paddingTop: SPACING.xs,
    flexGrow: 1,
  },
  createPlanContent: {
    paddingHorizontal: SPACING.container,
    paddingVertical: SPACING.element,
    paddingTop: SPACING.xs,
    gap: SPACING.xxl,
  },
  createPlanHeader: {
    paddingHorizontal: SPACING.container,
    paddingVertical: SPACING.element,
    backgroundColor: COLORS.white,
  },
  exercisesScrollContent: {
    paddingHorizontal: SPACING.container,
    paddingVertical: SPACING.element,
    gap: SPACING.medium,
  },
  formGroup: {
    marginBottom: SPACING.container,
  },
  label: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.small,
  },
  input: {
    backgroundColor: COLORS.secondaryBackground,
    borderRadius: SPACING.borderRadius,
    paddingHorizontal: SPACING.element,
    paddingVertical: SPACING.medium,
    fontSize: TYPOGRAPHY.sizes.lg,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  textArea: {
    textAlignVertical: "top",
    paddingVertical: SPACING.medium,
    minHeight: 100,
  },
  buttonGroup: {
    gap: SPACING.medium,
    marginTop: SPACING.xxxl,
  },
  buttonGroupFixed: {
    flexDirection: "row",
    gap: SPACING.medium,
    paddingHorizontal: SPACING.container,
    paddingVertical: SPACING.element,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  buttonHalf: {
    flex: 1,
  },
  buttonThird: {
    flex: 1,
  },
  cancelButton: {
    backgroundColor: COLORS.textSecondary,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  exercisesSection: {
    marginTop: 0,
    paddingTop: SPACING.xs,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.element,
  },
  headerActions: {
    flexDirection: "row",
    gap: SPACING.medium,
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
  },
  emptyExercisesText: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textSecondary,
    fontStyle: "italic",
    marginVertical: SPACING.element,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
    padding: 0,
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: SPACING.borderRadiusXL,
    borderTopRightRadius: SPACING.borderRadiusXL,
    padding: SPACING.xxl,
    width: "100%",
    paddingBottom: 40,
  },
  modalTitle: {
    fontSize: TYPOGRAPHY.sizes.xxl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.container,
  },
  rowGroup: {
    flexDirection: "row",
    gap: SPACING.medium,
    marginBottom: SPACING.container,
  },
  modalButtonGroup: {
    flexDirection: "row",
    gap: SPACING.medium,
    marginTop: SPACING.container,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  menuContent: {
    backgroundColor: COLORS.white,
    borderRadius: SPACING.borderRadiusXL,
    padding: 0,
    width: "80%",
    overflow: "hidden",
  },
  menuTitle: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    padding: SPACING.element,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.medium,
    padding: SPACING.element,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuItemText: {
    fontSize: TYPOGRAPHY.sizes.lg,
    color: COLORS.textPrimary,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  totalsCard: {
    backgroundColor: COLORS.primaryLight,
    margin: SPACING.element,
    padding: SPACING.element,
    borderRadius: SPACING.borderRadiusXL,
    borderWidth: 1,
    borderColor: "#B3D9F2",
  },
  totalsTitle: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.info,
    marginBottom: SPACING.medium,
  },
  totalsGrid: {
    flexDirection: "row",
    gap: SPACING.medium,
  },
  totalItem: {
    flex: 1,
    backgroundColor: COLORS.white,
    padding: SPACING.small,
    borderRadius: SPACING.borderRadius,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D1E7F5",
  },
  totalLabel: {
    fontSize: TYPOGRAPHY.sizes.xs,
    color: COLORS.textTertiary,
    fontWeight: TYPOGRAPHY.weights.medium,
    marginBottom: SPACING.xs,
  },
  totalValue: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.info,
  },
  goalText: {
    fontSize: TYPOGRAPHY.sizes.xs,
    color: COLORS.textSecondary,
    marginTop: SPACING.xs,
  },
  summaryCard: {
    backgroundColor: COLORS.secondaryBackground,
    marginVertical: SPACING.small,
    marginHorizontal: SPACING.element,
    paddingHorizontal: SPACING.element,
    paddingVertical: SPACING.element,
    borderRadius: SPACING.borderRadiusXL,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  summaryCardInner: {
    backgroundColor: COLORS.secondaryBackground,
  },
  summaryTitle: {
    ...TYPOGRAPHY.sectionTitle,
    marginBottom: 0,
  },
  summaryContent: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 0,
    marginTop: SPACING.small,
    justifyContent: "space-between",
    gap: SPACING.small,
  },
  summaryItem: {
    width: "48%",
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: COLORS.tertiaryBackground,
    borderRadius: SPACING.borderRadius,
    borderWidth: 1,
    borderColor: COLORS.tertiaryBackground,
    overflow: "hidden",
    position: "relative",
  },
  summaryItemProgressOverlay: {
    position: "absolute",
    left: -10,
    top: -10,
    right: -10,
    bottom: -10,
    opacity: 0.15,
    borderRadius: SPACING.borderRadius,
  },
  summaryLabel: {
    fontSize: TYPOGRAPHY.sizes.xs,
    color: COLORS.textPrimary,
    fontWeight: TYPOGRAPHY.weights.semibold,
    marginBottom: SPACING.xs,
  },
  summaryValue: {
    fontSize: TYPOGRAPHY.sizes.xl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  summaryGoal: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.info,
    fontWeight: TYPOGRAPHY.weights.semibold,
  },
  summaryValueRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: SPACING.xs,
  },
  summaryGoalSmall: {
    fontSize: TYPOGRAPHY.sizes.xs,
    color: COLORS.textSecondary,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  progressContainer: {
    borderTopWidth: 1.5,
    borderTopColor: "#e8e8e8",
    paddingTop: SPACING.element,
    gap: SPACING.medium,
  },
  progressItem: {
    marginBottom: 0,
  },
  progressLabel: {
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.small,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: "#e8e8e8",
    borderRadius: SPACING.borderRadiusSmall,
    overflow: "hidden",
    marginBottom: SPACING.small,
  },
  progressBar: {
    height: "100%",
    borderRadius: SPACING.borderRadiusSmall,
  },
  progressText: {
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textTertiary,
  },
  workoutsSection: {
    paddingHorizontal: SPACING.element,
    paddingVertical: SPACING.element,
    marginVertical: SPACING.small,
    backgroundColor: COLORS.secondaryBackground,
    borderRadius: SPACING.borderRadiusXL,
    marginHorizontal: SPACING.element,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  workoutsSectionTitle: {
    ...TYPOGRAPHY.sectionTitle,
    marginBottom: 0,
  },
  workoutsScrollView: {
    marginHorizontal: -16,
    paddingHorizontal: 16,
  },
  workoutsScrollContent: {
    gap: 12,
    paddingRight: 16,
    marginTop: 12,
  },
  workoutCard: {
    width: 160,
    backgroundColor: COLORS.tertiaryBackground,
    borderRadius: SPACING.borderRadiusXL,
    padding: SPACING.medium,
    borderWidth: 1.5,
    borderColor: COLORS.tertiaryBackground,
    justifyContent: "space-between",
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  workoutCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.small,
    marginBottom: SPACING.small,
  },
  workoutCardIcon: {
    padding: SPACING.small,
    backgroundColor: COLORS.tertiaryBackground,
    borderRadius: SPACING.borderRadiusLarge,
  },
  workoutCardName: {
    fontSize: TYPOGRAPHY.sizes.sm,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    flex: 1,
  },
  workoutCardStatus: {
    backgroundColor: COLORS.secondaryBackground,
    paddingVertical: SPACING.small,
    paddingHorizontal: SPACING.medium,
    borderRadius: SPACING.borderRadius,
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    width: "100%",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  workoutCardStatusCompleted: {
    backgroundColor: COLORS.secondaryLight,
    borderColor: COLORS.carbs,
  },
  workoutCardStatusText: {
    color: COLORS.warning,
    fontSize: TYPOGRAPHY.sizes.sm,
    fontWeight: TYPOGRAPHY.weights.semibold,
  },
  workoutCardStatusTextCompleted: {
    color: COLORS.success,
    fontSize: TYPOGRAPHY.sizes.sm,
    fontWeight: TYPOGRAPHY.weights.semibold,
  },
  mealsListContent: {
    paddingHorizontal: SPACING.container,
    paddingVertical: SPACING.element,
    gap: SPACING.medium,
  },
  categoryPicker: {
    flexDirection: "row",
    gap: SPACING.small,
    flexWrap: "wrap",
  },
  categoryButton: {
    paddingVertical: SPACING.small,
    paddingHorizontal: SPACING.element,
    borderRadius: SPACING.borderRadius,
    backgroundColor: COLORS.secondaryBackground,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  categoryButtonActive: {
    backgroundColor: COLORS.info,
    borderColor: "#0056D4",
  },
  categoryButtonText: {
    fontSize: TYPOGRAPHY.sizes.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textTertiary,
  },
  categoryButtonTextActive: {
    color: COLORS.white,
  },
  existingMealItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.secondaryBackground,
    paddingHorizontal: SPACING.element,
    paddingVertical: SPACING.element,
    marginHorizontal: SPACING.element,
    marginVertical: SPACING.xs,
    borderRadius: SPACING.borderRadiusLarge,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
    gap: SPACING.medium,
    flex: 1,
  },
  existingMealName: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  existingMealCategory: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textSecondary,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  existingMealNutrition: {
    flexDirection: "row",
    gap: SPACING.small,
  },
  existingMealNutritionText: {
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.info,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: SPACING.small,
    paddingVertical: SPACING.xs,
    borderRadius: SPACING.borderRadiusSmall,
  },
  existingMealContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.small,
    marginHorizontal: SPACING.element,
    marginVertical: SPACING.xs,
  },
  editMealButton: {
    backgroundColor: COLORS.info,
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  modalHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: SPACING.medium,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  editModeToggleButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: COLORS.info,
    justifyContent: "center",
    alignItems: "center",
  },
  editModeToggleButtonActive: {
    backgroundColor: COLORS.info,
    borderColor: COLORS.info,
  },
  confirmIconContainer: {
    alignItems: "center",
    marginBottom: SPACING.element,
  },
  mealNameConfirm: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
    textAlign: "center",
    marginBottom: SPACING.element,
  },
  confirmNutritionGrid: {
    flexDirection: "row",
    gap: SPACING.medium,
    marginBottom: SPACING.xxl,
    flexWrap: "wrap",
  },
  confirmNutritionItem: {
    flex: 1,
    minWidth: "48%",
    backgroundColor: COLORS.secondaryBackground,
    paddingVertical: SPACING.small,
    paddingHorizontal: SPACING.medium,
    borderRadius: SPACING.borderRadius,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  confirmNutritionLabel: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textTertiary,
    fontWeight: TYPOGRAPHY.weights.medium,
    marginBottom: SPACING.xs,
  },
  confirmNutritionValue: {
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.success,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.xxxl,
  },
  mealItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.white,
    paddingVertical: SPACING.element,
    paddingHorizontal: SPACING.element,
    borderRadius: SPACING.borderRadiusLarge,
    marginBottom: SPACING.medium,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  mealItemName: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  mealItemMacros: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textTertiary,
    fontWeight: TYPOGRAPHY.weights.regular,
  },
  macroGridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.medium,
  },
  macroCard: {
    width: "48%",
    backgroundColor: COLORS.secondaryBackground,
    borderRadius: SPACING.borderRadiusLarge,
    padding: SPACING.medium,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  macroLabel: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textTertiary,
    fontWeight: TYPOGRAPHY.weights.medium,
    marginBottom: SPACING.xs,
  },
  macroValue: {
    fontSize: TYPOGRAPHY.sizes.xxl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.info,
    marginBottom: SPACING.xs,
  },
  macroGoal: {
    fontSize: TYPOGRAPHY.sizes.xs,
    color: COLORS.textSecondary,
    fontWeight: TYPOGRAPHY.weights.regular,
  },
  dateHeader: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.medium,
    color: COLORS.textTertiary,
  },
  progressTabsContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.tertiaryBackground,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.mediumGray,
  },
  progressTab: {
    flex: 1,
    paddingVertical: SPACING.element,
    alignItems: "center",
    borderBottomWidth: 3,
    borderBottomColor: "transparent",
  },
  progressTabActive: {
    borderBottomColor: COLORS.info,
  },
  progressTabText: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textTertiary,
  },
  progressTabTextActive: {
    color: COLORS.info,
  },
  progressContentContainer: {
    flex: 1,
  },
});

// ============================================================================
// LOG MEALS SCREEN STYLES
// ============================================================================

export const logMealsScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    paddingTop: 0,
    backgroundColor: COLORS.mainBackground,
  },
  dateHeader: {
    paddingHorizontal: SPACING.element,
    paddingBottom: SPACING.xs,
  },
  dateText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontWeight: "500",
  },
  buttonsContainer: {
    flexDirection: "row",
    paddingHorizontal: SPACING.element,
    paddingVertical: SPACING.element,
    backgroundColor: COLORS.mainBackground,
    gap: SPACING.element,
    borderTopWidth: 1,
    borderTopColor: COLORS.mediumGray,
    justifyContent: "center",
    alignItems: "center",
  },
});

// ============================================================================
// FORM STYLES (For MealForm and other forms)
// ============================================================================

export const formStyles = StyleSheet.create({
  formGroup: {
    marginBottom: SPACING.container,
  },
  label: {
    ...TYPOGRAPHY.label,
    color: COLORS.textPrimary,
    marginBottom: SPACING.small,
  },
  input: {
    backgroundColor: COLORS.secondaryBackground,
    borderRadius: SPACING.borderRadius,
    paddingHorizontal: SPACING.element,
    paddingVertical: SPACING.medium,
    fontSize: TYPOGRAPHY.sizes.lg,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  rowGroup: {
    flexDirection: "row",
    gap: SPACING.medium,
    marginBottom: SPACING.container,
  },
  mealTypeButton: {
    width: "48%",
    paddingVertical: SPACING.small,
    paddingHorizontal: SPACING.small,
    borderRadius: SPACING.borderRadius,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: SPACING.xs,
  },
  mealTypeButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
  },
  mealTypeButtonInactive: {
    borderColor: COLORS.mediumGray,
    backgroundColor: COLORS.secondaryBackground,
  },
  mealTypeButtonText: {
    ...TYPOGRAPHY.small,
    fontWeight: TYPOGRAPHY.weights.semibold,
  },
  mealTypeButtonTextActive: {
    color: COLORS.white,
  },
  mealTypeButtonTextInactive: {
    color: COLORS.textPrimary,
  },
  helperText: {
    ...TYPOGRAPHY.small,
    color: COLORS.textSecondary,
    marginTop: SPACING.small,
  },
});

// FAB styles
export const fabStyles = StyleSheet.create({
  tabBarIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    marginTop: SPACING.medium,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderRadius: SPACING.borderRadiusXL,
    padding: SPACING.xxl,
    width: "80%",
    maxWidth: 300,
    gap: SPACING.element,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.element,
    paddingVertical: SPACING.element,
    paddingHorizontal: SPACING.medium,
    borderRadius: SPACING.borderRadiusLarge,
    backgroundColor: COLORS.secondaryBackground,
    borderWidth: 1,
    borderColor: COLORS.mediumGray,
  },
  modalOptionText: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
  },
});
